# Authentication profile for reading the emails
send: 
  # To use Oauth2, you need to register an application in Azure AD and grant the necessary permissions:
  # https://ecederstrand.github.io/exchangelib/#oauth-authentication 
  # To grant admin consent ot use an application: https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent?pivots=portal#construct-the-url-for-granting-tenant-wide-admin-consent
  # I had troubles using basic oauth2, so for now, the software only supports oauth2legacy
  oauth2legacy:
    email: <user@phishingdomain.com>
    password: <userpassword>
    client_id: <your client id>
    client_secret: <your client secret>
    tenant_id: <your tenant id>
  # smtp:
  #   username: <user@phishingdomain.com>
  #   password: <userpassword>
  #   server:  <smtp.yourdomain.com>
  #   port: 587
  #   tls: True
# Authentication profile for sending out emails
read:
  imap:
    username: <usercatchall@catchallserver.com>
    password: <usercatchallpassword>
    server: <imap.catchallserver.com>
    port: 993
    ssl: True
